---
- name: "Installing required packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      - {name: "gdm3"} # Is a Display Manager.
      - {name: "ubuntu-desktop-minimal"} # GUI of the Ubuntu with just the necessary applications.
      - {name: "libnss3-tools"} # To use the certutil tool.
      - {name: "network-manager"} # Ubuntu Desktop uses a different network manager.
      - {name: "network-manager-gnome"} # Ubuntu Desktop uses a different network manager.
